services:
  postgres:
    image: postgres:16
    container_name: bazar-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: bazar_api
      POSTGRES_USER: bazar_user
      POSTGRES_PASSWORD: bazar_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bazar_user -d bazar_api"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 25s

volumes:
  postgres_data: