services:
  mysql:
    image: mysql:8.4
    container_name: bazar-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: bazar_api
      MYSQL_USER: bazar_user
      MYSQL_PASSWORD: bazar_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 25s

volumes:
  mysql_data:
