spring:
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: false
        boot:
          allow_jdbc_metadata_access: false
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 2